// Array con i nomi di tutte le immagini in Cards-jpg e una breve descrizione
export const cardImageNames = [
    ["00-IlMatto", "Inizio, spontaneità, nuove possibilità, follia, libertà."],
    ["01-IlMago", "Volontà, creatività, manifestazione, abilità."],
    ["02-LaPapessa", "Intuizione, mistero, saggezza interiore, segreti."],
    ["03-LImperatrice", "Fertilità, abbondanza, creatività, madre, natura."],
    ["04-LImperatore", "Autorità, stabilità, struttura, potere, padre."],
    ["05-IlPapa", "Tradizione, spiritualità, insegnamento, guida morale."],
    ["06-GliAmanti", "Scelta, amore, unione, relazioni, armonia."],
    ["07-IlCarro", "Vittoria, determinazione, controllo, viaggio."],
    ["08-LaForza", "Coraggio, forza interiore, compassione, dominio di sé."],
    ["09-LEremita", "Ricerca interiore, solitudine, saggezza, introspezione."],
    ["10-LaRuotaDellaFortuna", "Destino, cambiamento, cicli, fortuna."],
    ["11-LaGiustizia", "Equità, verità, responsabilità, legge, karma."],
    ["12-LAppeso", "Attesa, sacrificio, nuova prospettiva, sospensione."],
    ["13-LaMorte", "Trasformazione, fine, rinascita, cambiamento radicale."],
    ["14-LaTemperanza", "Equilibrio, armonia, pazienza, guarigione."],
    ["15-IlDiavolo", "Dipendenza, materialismo, tentazione, ombra."],
    ["16-LaTorre", "Crollo, crisi, rivelazione, cambiamento improvviso."],
    ["17-LaStella", "Speranza, ispirazione, serenità, guarigione."],
    ["18-LaLuna", "Illusione, sogni, inconscio, confusione."],
    ["19-IlSole", "Gioia, successo, vitalità, chiarezza."],
    ["20-IlGiudizio", "Rinascita, risveglio, decisione, redenzione."],
    ["21-IlMondo", "Completamento, realizzazione, viaggio concluso."],
    ["Coppe01", "Nuovo inizio emotivo, potenziale per amore o amicizia."],
    ["Coppe02", "Unione, collaborazione, relazione armoniosa."],
    ["Coppe03", "Celebrazione, amicizia, gioia condivisa."],
    ["Coppe04", "Insoddisfazione, apatia, riflessione emotiva."],
    ["Coppe05", "Perdita, rimpianto, tristezza, delusione."],
    ["Coppe06", "Nostalgia, ricordi, infanzia, ritorno al passato."],
    ["Coppe07", "Scelte, illusioni, sogni, confusione emotiva."],
    ["Coppe08", "Allontanamento, ricerca di significato, abbandono."],
    ["Coppe09", "Soddisfazione, desiderio realizzato, appagamento."],
    ["Coppe10", "Felicità familiare, armonia, benedizione."],
    ["Coppe11", "Messaggio emotivo, creatività, sensibilità."],
    ["Coppe12", "Romanticismo, idealismo, offerta d'amore."],
    ["Coppe13", "Maturità emotiva, compassione, saggezza."],
    ["Coppe14", "Equilibrio emotivo, moderazione, diplomazia."],
    ["Denari01", "Nuovo inizio materiale, opportunità finanziaria."],
    ["Denari02", "Equilibrio tra risorse, adattabilità, flessibilità."],
    ["Denari03", "Collaborazione, lavoro di squadra, abilità."],
    ["Denari04", "Attaccamento, sicurezza materiale, possessività."],
    ["Denari05", "Difficoltà finanziarie, esclusione, povertà."],
    ["Denari06", "Generosità, aiuto, condivisione delle risorse."],
    ["Denari07", "Attesa, valutazione, crescita lenta."],
    ["Denari08", "Impegno, perfezionamento, apprendimento."],
    ["Denari09", "Successo materiale, indipendenza, gratificazione."],
    ["Denari10", "Ricchezza familiare, eredità, stabilità."],
    ["Denari11", "Nuovo messaggio pratico, studio, apprendimento."],
    ["Denari12", "Progresso, determinazione, lavoro costante."],
    ["Denari13", "Maturità materiale, affidabilità, sicurezza."],
    ["Denari14", "Gestione saggia delle risorse, generosità."],
    ["Spade01", "Nuova idea, chiarezza mentale, verità."],
    ["Spade02", "Scelta difficile, indecisione, equilibrio mentale."],
    ["Spade03", "Dolore, delusione, cuore spezzato."],
    ["Spade04", "Riposo, recupero, riflessione."],
    ["Spade05", "Conflitto, sconfitta, tensione."],
    ["Spade06", "Transizione, viaggio, cambiamento."],
    ["Spade07", "Inganno, strategia, furtività."],
    ["Spade08", "Limitazione, blocco mentale, restrizione."],
    ["Spade09", "Ansia, preoccupazione, insonnia."],
    ["Spade10", "Fine dolorosa, tradimento, conclusione."],
    ["Spade11", "Nuovo messaggio mentale, curiosità, apprendimento."],
    ["Spade12", "Azione rapida, determinazione, coraggio."],
    ["Spade13", "Maturità mentale, autorità, verità."],
    ["Spade14", "Saggezza, equilibrio, giustizia mentale."],
    ["Bastoni01", "Nuovo inizio creativo, ispirazione, energia."],
    ["Bastoni02", "Pianificazione, visione, decisione."],
    ["Bastoni03", "Espansione, progresso, opportunità."],
    ["Bastoni04", "Celebrazione, stabilità, successo domestico."],
    ["Bastoni05", "Competizione, conflitto, sfida."],
    ["Bastoni06", "Vittoria, riconoscimento, successo pubblico."],
    ["Bastoni07", "Difesa, coraggio, perseveranza."],
    ["Bastoni08", "Rapidità, movimento, comunicazione."],
    ["Bastoni09", "Resilienza, difesa, fatica."],
    ["Bastoni10", "Sovraccarico, responsabilità, fatica."],
    ["Bastoni11", "Nuovo messaggio creativo, entusiasmo."],
    ["Bastoni12", "Azione, avventura, passione."],
    ["Bastoni13", "Maturità creativa, leadership, visione."],
    ["Bastoni14", "Saggezza creativa, generosità, ispirazione."]
];

